services:
  - type: web
    name: afya-quest-backend
    env: node
    rootDir: afya-quest-backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        # Set in Render dashboard to your MongoDB Atlas connection string
        value: ""
      - key: JWT_SECRET
        # Generate a strong secret in Render dashboard
        generateValue: true
      - key: OPENAI_API_KEY
        # Optional: only needed for /api/chat assistant
        value: ""
      - key: OPENAI_MODEL
        value: gpt-4o-mini
